### PR TITLE
added tiles.html

### PR DESCRIPTION
**Pull request by quickhand**

### CODE REVIEW

**Comment by quickhand** [comment]
Fixed. Sorry, my auto-formatter got carried away.

**Comment by Metroxe** [comment]
image

lol could only solve the simplest puzzle. I like it a lot!!

**Comment by quickhand** [comment]
Max I've solved is the 5x5 :)

**Comment by Metroxe** [comment]
image

**Comment by quickhand** [comment]
Nice! :)

**Pull request merged**
